GLOSSIKA_EN = 'Glossika/EN/'
GLOSSIKA_VN = 'Glossika/VN/'
ACCENT_VN = 'Accent/AccentVN'
ACCENT_EN = 'Accent/AccentEN'
GRAMMAR_VN = 'Grammar/GrammarVN'
GRAMMAR_EN = 'Grammar/GrammarEN'
GLOSSIKA_OVERVIEW = './Overview(wav)/'
